name: crudrepo
description: A package for managing CRUD operations with a repository pattern in Flutter.
version: 0.2.0
repository: https://github.com/gabrielgits/crudrepo.git

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  result_dart: ^2.1.1
  sqflite: ^2.4.2
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.6
  build_runner: ^2.5.2
